version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_NAME=CRM BhConnect
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost:8080
      - APP_KEY=base64:PKGJbGg/WRENhBrcAHRWtvLOCzTszrtyfzGoh1j9xP8=
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=crm_bhconnect
      - DB_USERNAME=root
      - DB_PASSWORD=password
    depends_on:
      - mysql
    volumes:
      - .:/app
      - /app/vendor

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=crm_bhconnect
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
