[build]
  publish = "public"
  command = "composer install --optimize-autoloader --no-dev && npm install && npm run build"

[build.environment]
  PHP_VERSION = "8.1"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200

[context.production.environment]
  APP_ENV = "production"
  APP_DEBUG = "false"
  APP_NAME = "CRM BhConnect"
  APP_URL = "https://crm-bhconnect.netlify.app"

[context.deploy-preview.environment]
  APP_ENV = "staging"
  APP_DEBUG = "true"
  APP_NAME = "CRM BhConnect (Preview)"
  APP_URL = "https://deploy-preview-{BRANCH}--crm-bhconnect.netlify.app"
